services:
  - type: web
    name: pdf-ai-extractor
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: gunicorn app:app